version: '3'
services:
  api:
    hostname: api
    container_name: api
    build: application/
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - TZ=Asia/Almaty
      - PYTHONUNBUFFERED=1
    restart: always
    ports:
      - "9001:9001"
    logging:
      options:
        max-size: 50m

