version: '3.8'

services:
  license-plate-api:
    build: .
    container_name: license-plate-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - MAX_WORKERS=4
      - TIMEOUT=120
    command: >
      uvicorn src.main:app 
      --host 0.0.0.0 
      --port 8000 
      --workers 4 
      --timeout-keep-alive 120